# The Docker image that will be used to build your app
image: node:lts

cache:
  paths:
    - ./node_modules/

pages:
  before_script:
    - CI=false npm install
  script:
    - CI=false npm run build
    - test -d ./public && rm -rf ./public
    - mv ./build ./public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
